### ISSUE TITLE
Content to show on the notification pop up

### ISSUE THREAD

**Issue by alsongarbuja** [GCES-Batch-2018-Minor-project-group/cabavenue#4]
Yesto notification pop up

![Image](https://user-images.githubusercontent.com/42911859/173757654-cfc385df-ca2d-4bd4-85c2-80bc877ae1df.png)

**Comment by Alson33** [comment]
Hamro chai 2 tah case mah auxa hai

1. Ride accept huda
2. Ride reject huda
